apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitlog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitlog
  template:
    metadata:
      labels:
        app: fitlog
    spec:
      containers:
      - name: django
        image: seiedsi/fitlog:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_ENV
          value: "production"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10