apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitlog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitlog
  template:
    metadata:
      labels:
        app: fitlog
    spec:
      containers:
      - name: django
        image: seiedsi/fitlog:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /signup/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10