apiVersion: v1
kind: Service
metadata:
  name: fitlog-service
spec:
  selector:
    app: fitlog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Use NodePort for Minikube