name: Django Kubernetes Deployment

on:
  push:
    branches: [ main ]

jobs:
  setup-minikube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Minikube
      run: |
        sudo apt-get update -q
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        sudo apt-get install -y conntrack
        
    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube update-context
        cat ~/.kube/config | base64 -w0 >> $GITHUB_OUTPUT
      id: minikube-config

  build:
    needs: setup-minikube
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      working-directory: ./app
      run: |
        eval $(minikube -p minikube docker-env)
        docker build -t fitlog .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        echo '${{ needs.setup-minikube.outputs.minikube-config }}' | base64 --decode > ~/.kube/config
        kubectl cluster-info