name: Django Kubernetes Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      working-directory: ./app
      run: |
        docker build -t fitlog .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-kubectl@v3
    
    - name: Configure Kubernetes access
      run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ~/.kube/config

          sed -i 's|C:\\\\Users\\\\WINDOWS\\\\.minikube|/home/runner/.minikube|g' ~/.kube/config
          sed -i 's|\\\\|/|g' ~/.kube/config
          chmod 600 ~/.kube/config

    - name: Deploy to Kubernetes
      working-directory: ./k8s
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl rollout status deployment/fitlog